server:
  port: 8081
  servlet:
    path: /movie-api/*

spring:
  application:
    name: microservice-consumer-movie
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://nsk:abcd1234@localhost:8764/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

